apiVersion: route53.takutakahashi.dev/v1
kind: HealthCheck
metadata:
  name: healthcheck-sample
spec:
  enabled: true
  protocol: "HTTPS"
  invert: false
  port: 443
  path: "/"
  failureThreshold: 1
  endpoint:
    address: 8.8.8.8
  features:
    fastInterval: true
